<?php
$z[0]=Array("global","",205,237);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",288,320);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",373,405);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("include","",441,476);
$z[3][4]['filename']="head.htm";
$z[4]=Array("global","",565,597);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",2667,2704);
$z[5][4]['filename']="footer.htm";
$z[6]=Array("global","",4611,4643);
$z[6][4]['name']="cfg_templets_skin";

?>