<?php  exit();
/*
Page: /dede/login.php
Error: 无法使用数据库
Time2018-01-02 11:05:32
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: No database selected <br />Error sql: <font color='red'>SELECT admin.*,atype.purviews FROM `dede_admin` admin LEFT JOIN `dede_admintype` atype ON atype.rank=admin.usertype WHERE admin.userid LIKE 'admin' LIMIT 0,1</font>
Time2018-01-02 11:05:32
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: 无法使用数据库
Time2018-01-02 11:05:36
*/
?>
<?php  exit();
/*
Page: /dede/login.php
Error: No database selected <br />Error sql: <font color='red'>SELECT admin.*,atype.purviews FROM `dede_admin` admin LEFT JOIN `dede_admintype` atype ON atype.rank=admin.usertype WHERE admin.userid LIKE 'admin' LIMIT 0,1</font>
Time2018-01-02 11:05:36
*/
?>
